import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { lazy, Suspense } from 'react';
import GetCurrentUser from "./(auth)/actions/GetCurrentUser";
import CartContext from "../Context/CartContext";
const Navbar = lazy(()=> import('../components/Navbar'))
const Footer = lazy(()=> import('../components/Footer'))
const AuthContext = lazy(()=> import('../Context/AuthContext'))
const ToasterContext = lazy(()=> import('../Context/ToasterContext'))
const Scroll = lazy(()=> import('../components/Scroll'))

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await GetCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<div>Loading...</div>}>
        <AuthContext>
          <CartContext>
            <ToasterContext />
            <Navbar user={user!} />
            <Scroll />
            {children}
            <Footer />
          </CartContext>
        </AuthContext>
        </Suspense>
      </body>
    </html>
  );
}
