import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import AuthContext from "@/Context/AuthContext";
import getCurrentUser from "./(auth)/actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Root({children,}:{children:React.ReactNode}) {
  const user = await getCurrentUser()
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>

        <Navbar user={user!}/>
        </AuthContext>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
